name: Neuen Onlineshop hinzufügen
description: Schlage einen neuen Onlineshop vor
title: "[Shop]: "
labels: ["enhancement", "shop"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: url
    attributes:
      label: Shop URL
      description: Wie lautet die URL des Shops?
    validations:
      required: true
  - type: input
    id: setSelector
    attributes:
      label: Set Nummer CSS Selektor
      description: Wo befindet sich auf der Shopseite die LEGO Set Nummer?
    validations:
      required: true
    